genome: NCBI-hg38 # one of NCBI-hg38
blacklist: path/to/blacklist
samples:
  mm1s:
    fastq:
      r1:
        - ftp.sra.ebi.ac.uk/vol1/fastq/SRR335/001/SRR3356451/SRR3356451_1.fastq.gz
      r2:
        - ftp.sra.ebi.ac.uk/vol1/fastq/SRR335/001/SRR3356451/SRR3356451_2.fastq.gz
